# Generated by Django 5.1.6 on 2025-02-13 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_alter_booking_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
